/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_jewsaten_ndksample_AESUtils */

#ifndef _Included_io_jewsaten_ndksample_AESUtils
#define _Included_io_jewsaten_ndksample_AESUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_jewsaten_ndksample_AESUtils
 * Method:    AESEncode
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_jewsaten_ndksample_AESUtils_AESEncode
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     io_jewsaten_ndksample_AESUtils
 * Method:    AESDecode
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_jewsaten_ndksample_AESUtils_AESDecode
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
