/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_jewsaten_ndksample_AESUtils */

#ifndef _Included_io_jewsaten_ndksample_AESUtils
#define _Included_io_jewsaten_ndksample_AESUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_jewsaten_ndksample_AESUtils
 * Method:    AESEncode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_jewsaten_ndksample_AESUtils_AESEncode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_jewsaten_ndksample_AESUtils
 * Method:    AESDecode
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_jewsaten_ndksample_AESUtils_AESDecode
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
